import axios from 'axios';
import Head from 'next/head'
import "bootstrap/dist/css/bootstrap.min.css";
import Image from 'next/image'
import Featured from '../components/Featured';
import PizzaList from '../components/PizzaList';
import styles from '../styles/Home.module.css';
import OrderDetaild from '../components/OrderDetaild';
export default function Home({pizzaList, admin}) {
  return (
    <div>
      <Head>
        <title>Food App</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
      
        <Featured />
        {admin && <span>Hello</span>}
        <PizzaList pizzaList={pizzaList} />
       
       </>
    </div>
  );
}
export const getServerSideProps = async (ctx) => {
  const myCookie = ctx.req?.cookies || "";
  let admin = false;

  if (myCookie.token === process.env.TOKEN) {
    admin = true;
  }
  const res = await axios.get("/api/products");
  return {
    props: {
      pizzaList: res.data,
    }
  }
}